version: "3"

services:
  transactions_db:
    container_name: db
    image: postgres:16rc1-alpine3.18
    restart: always
    volumes:
      - transactions_db:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  transactions_db:
    external: true
